services:
  # 1. API Gateway (Public Web Service)
  - type: web
    name: api-gateway
    plan: free
    runtime: go
    buildCommand: go build -o api-gateway ./services/api-gateway
    startCommand: ./api-gateway
    envVars:
      - key: PORT
        value: 8000
      - key: USER_SERVICE_ADDR
        value: users-service-wbz9:8080
      - key: ORDER_SERVICE_ADDR
        value: orders-service-wbz9:8080

  # 2. Users Service (Public Web Service - Free Tier)
  - type: web
    name: users-service
    plan: free
    runtime: go
    buildCommand: go build -o users-service ./services/users
    startCommand: ./users-service
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false # Puts a prompt in Render to paste the 'External Database URL'
