// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: tribecart/v1/orders.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order status enumeration
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PROCESSING  OrderStatus = 2
	OrderStatus_ORDER_STATUS_SHIPPED     OrderStatus = 3
	OrderStatus_ORDER_STATUS_DELIVERED   OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 5
	OrderStatus_ORDER_STATUS_REFUNDED    OrderStatus = 6
	OrderStatus_ORDER_STATUS_FAILED      OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PROCESSING",
		3: "ORDER_STATUS_SHIPPED",
		4: "ORDER_STATUS_DELIVERED",
		5: "ORDER_STATUS_CANCELLED",
		6: "ORDER_STATUS_REFUNDED",
		7: "ORDER_STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PROCESSING":  2,
		"ORDER_STATUS_SHIPPED":     3,
		"ORDER_STATUS_DELIVERED":   4,
		"ORDER_STATUS_CANCELLED":   5,
		"ORDER_STATUS_REFUNDED":    6,
		"ORDER_STATUS_FAILED":      7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tribecart_v1_orders_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_tribecart_v1_orders_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{0}
}

// Payment method enumeration
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_DEBIT_CARD  PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_NET_BANKING PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_UPI         PaymentMethod = 4
	PaymentMethod_PAYMENT_METHOD_COD         PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_DEBIT_CARD",
		3: "PAYMENT_METHOD_NET_BANKING",
		4: "PAYMENT_METHOD_UPI",
		5: "PAYMENT_METHOD_COD",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CREDIT_CARD": 1,
		"PAYMENT_METHOD_DEBIT_CARD":  2,
		"PAYMENT_METHOD_NET_BANKING": 3,
		"PAYMENT_METHOD_UPI":         4,
		"PAYMENT_METHOD_COD":         5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_tribecart_v1_orders_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_tribecart_v1_orders_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{1}
}

// Order item represents a single product in an order
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Discount      float64                `protobuf:"fixed64,5,opt,name=discount,proto3" json:"discount,omitempty"`
	Tax           float64                `protobuf:"fixed64,6,opt,name=tax,proto3" json:"tax,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,7,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Sku           string                 `protobuf:"bytes,8,opt,name=sku,proto3" json:"sku,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *OrderItem) GetTax() float64 {
	if x != nil {
		return x.Tax
	}
	return 0
}

func (x *OrderItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *OrderItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// Shipping address for the order
type ShippingAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AddressLine1  string                 `protobuf:"bytes,3,opt,name=address_line1,json=addressLine1,proto3" json:"address_line1,omitempty"`
	AddressLine2  string                 `protobuf:"bytes,4,opt,name=address_line2,json=addressLine2,proto3" json:"address_line2,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	IsDefault     bool                   `protobuf:"varint,10,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingAddress) Reset() {
	*x = ShippingAddress{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingAddress) ProtoMessage() {}

func (x *ShippingAddress) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingAddress.ProtoReflect.Descriptor instead.
func (*ShippingAddress) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *ShippingAddress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShippingAddress) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ShippingAddress) GetAddressLine1() string {
	if x != nil {
		return x.AddressLine1
	}
	return ""
}

func (x *ShippingAddress) GetAddressLine2() string {
	if x != nil {
		return x.AddressLine2
	}
	return ""
}

func (x *ShippingAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ShippingAddress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ShippingAddress) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ShippingAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *ShippingAddress) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ShippingAddress) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

// Order represents a complete order in the system
type Order struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNumber        string                 `protobuf:"bytes,3,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	Items              []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal           float64                `protobuf:"fixed64,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	ShippingCost       float64                `protobuf:"fixed64,6,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	TaxAmount          float64                `protobuf:"fixed64,7,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	DiscountAmount     float64                `protobuf:"fixed64,8,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	TotalAmount        float64                `protobuf:"fixed64,9,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status             OrderStatus            `protobuf:"varint,10,opt,name=status,proto3,enum=tribecart.v1.OrderStatus" json:"status,omitempty"`
	PaymentMethod      PaymentMethod          `protobuf:"varint,11,opt,name=payment_method,json=paymentMethod,proto3,enum=tribecart.v1.PaymentMethod" json:"payment_method,omitempty"`
	PaymentId          string                 `protobuf:"bytes,12,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ShippingAddressId  string                 `protobuf:"bytes,13,opt,name=shipping_address_id,json=shippingAddressId,proto3" json:"shipping_address_id,omitempty"`
	ShippingAddress    *ShippingAddress       `protobuf:"bytes,14,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	TrackingNumber     string                 `protobuf:"bytes,15,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier            string                 `protobuf:"bytes,16,opt,name=carrier,proto3" json:"carrier,omitempty"`
	OrderedAt          *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=ordered_at,json=orderedAt,proto3" json:"ordered_at,omitempty"`
	ShippedAt          *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=shipped_at,json=shippedAt,proto3" json:"shipped_at,omitempty"`
	DeliveredAt        *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	CancelledAt        *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CancellationReason string                 `protobuf:"bytes,21,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,22,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *Order) GetShippingCost() float64 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *Order) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *Order) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Order) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *Order) GetShippingAddressId() string {
	if x != nil {
		return x.ShippingAddressId
	}
	return ""
}

func (x *Order) GetShippingAddress() *ShippingAddress {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *Order) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Order) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *Order) GetOrderedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderedAt
	}
	return nil
}

func (x *Order) GetShippedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ShippedAt
	}
	return nil
}

func (x *Order) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Order) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

func (x *Order) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

func (x *Order) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request to create a new order
type CreateOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items             []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ShippingAddressId string                 `protobuf:"bytes,3,opt,name=shipping_address_id,json=shippingAddressId,proto3" json:"shipping_address_id,omitempty"`
	PaymentMethod     PaymentMethod          `protobuf:"varint,4,opt,name=payment_method,json=paymentMethod,proto3,enum=tribecart.v1.PaymentMethod" json:"payment_method,omitempty"`
	PaymentId         string                 `protobuf:"bytes,5,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CouponCode        string                 `protobuf:"bytes,6,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	Notes             string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetShippingAddressId() string {
	if x != nil {
		return x.ShippingAddressId
	}
	return ""
}

func (x *CreateOrderRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *CreateOrderRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreateOrderRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *CreateOrderRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// Request to get an order by ID
type GetOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeItems   bool                   `protobuf:"varint,2,opt,name=include_items,json=includeItems,proto3" json:"include_items,omitempty"`
	IncludeAddress bool                   `protobuf:"varint,3,opt,name=include_address,json=includeAddress,proto3" json:"include_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderRequest) GetIncludeItems() bool {
	if x != nil {
		return x.IncludeItems
	}
	return false
}

func (x *GetOrderRequest) GetIncludeAddress() bool {
	if x != nil {
		return x.IncludeAddress
	}
	return false
}

// Request to list orders with filters
type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=tribecart.v1.OrderStatus" json:"status,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	OrderBy       string                 `protobuf:"bytes,7,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Desc          bool                   `protobuf:"varint,8,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *ListOrdersRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

func (x *ListOrdersRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListOrdersRequest) GetDesc() bool {
	if x != nil {
		return x.Desc
	}
	return false
}

// Response for listing orders
type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListOrdersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Request to update order status
type UpdateOrderStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=tribecart.v1.OrderStatus" json:"status,omitempty"`
	Notes          string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,4,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Carrier        string                 `protobuf:"bytes,5,opt,name=carrier,proto3" json:"carrier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *UpdateOrderStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

// Request to cancel an order
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RefundPayment bool                   `protobuf:"varint,3,opt,name=refund_payment,json=refundPayment,proto3" json:"refund_payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{8}
}

func (x *CancelOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelOrderRequest) GetRefundPayment() bool {
	if x != nil {
		return x.RefundPayment
	}
	return false
}

// Request to get order history for a user
type GetOrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=tribecart.v1.OrderStatus" json:"status,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderHistoryRequest) Reset() {
	*x = GetOrderHistoryRequest{}
	mi := &file_tribecart_v1_orders_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderHistoryRequest) ProtoMessage() {}

func (x *GetOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_orders_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_orders_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrderHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetOrderHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *GetOrderHistoryRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *GetOrderHistoryRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *GetOrderHistoryRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

var File_tribecart_v1_orders_proto protoreflect.FileDescriptor

const file_tribecart_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\x19tribecart/v1/orders.proto\x12\ftribecart.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xf7\x01\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bdiscount\x18\x05 \x01(\x01R\bdiscount\x12\x10\n" +
	"\x03tax\x18\x06 \x01(\x01R\x03tax\x12\x1f\n" +
	"\vtotal_price\x18\a \x01(\x01R\n" +
	"totalPrice\x12\x10\n" +
	"\x03sku\x18\b \x01(\tR\x03sku\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\"\xaf\x02\n" +
	"\x0fShippingAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12#\n" +
	"\raddress_line1\x18\x03 \x01(\tR\faddressLine1\x12#\n" +
	"\raddress_line2\x18\x04 \x01(\tR\faddressLine2\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\x12!\n" +
	"\fphone_number\x18\t \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"is_default\x18\n" +
	" \x01(\bR\tisDefault\"\x98\t\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\forder_number\x18\x03 \x01(\tR\vorderNumber\x12-\n" +
	"\x05items\x18\x04 \x03(\v2\x17.tribecart.v1.OrderItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x05 \x01(\x01R\bsubtotal\x12#\n" +
	"\rshipping_cost\x18\x06 \x01(\x01R\fshippingCost\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\a \x01(\x01R\ttaxAmount\x12'\n" +
	"\x0fdiscount_amount\x18\b \x01(\x01R\x0ediscountAmount\x12!\n" +
	"\ftotal_amount\x18\t \x01(\x01R\vtotalAmount\x121\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x19.tribecart.v1.OrderStatusR\x06status\x12B\n" +
	"\x0epayment_method\x18\v \x01(\x0e2\x1b.tribecart.v1.PaymentMethodR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"payment_id\x18\f \x01(\tR\tpaymentId\x12.\n" +
	"\x13shipping_address_id\x18\r \x01(\tR\x11shippingAddressId\x12H\n" +
	"\x10shipping_address\x18\x0e \x01(\v2\x1d.tribecart.v1.ShippingAddressR\x0fshippingAddress\x12'\n" +
	"\x0ftracking_number\x18\x0f \x01(\tR\x0etrackingNumber\x12\x18\n" +
	"\acarrier\x18\x10 \x01(\tR\acarrier\x129\n" +
	"\n" +
	"ordered_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\torderedAt\x129\n" +
	"\n" +
	"shipped_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tshippedAt\x12=\n" +
	"\fdelivered_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x12=\n" +
	"\fcancelled_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\x12/\n" +
	"\x13cancellation_reason\x18\x15 \x01(\tR\x12cancellationReason\x12=\n" +
	"\bmetadata\x18\x16 \x03(\v2!.tribecart.v1.Order.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12-\n" +
	"\x05items\x18\x02 \x03(\v2\x17.tribecart.v1.OrderItemR\x05items\x12.\n" +
	"\x13shipping_address_id\x18\x03 \x01(\tR\x11shippingAddressId\x12B\n" +
	"\x0epayment_method\x18\x04 \x01(\x0e2\x1b.tribecart.v1.PaymentMethodR\rpaymentMethod\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x05 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vcoupon_code\x18\x06 \x01(\tR\n" +
	"couponCode\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"o\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rinclude_items\x18\x02 \x01(\bR\fincludeItems\x12'\n" +
	"\x0finclude_address\x18\x03 \x01(\bR\x0eincludeAddress\"\xb8\x02\n" +
	"\x11ListOrdersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.tribecart.v1.OrderStatusR\x06status\x127\n" +
	"\tfrom_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\x12\x19\n" +
	"\border_by\x18\a \x01(\tR\aorderBy\x12\x12\n" +
	"\x04desc\x18\b \x01(\bR\x04desc\"\x8a\x01\n" +
	"\x12ListOrdersResponse\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.tribecart.v1.OrderR\x06orders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xb6\x01\n" +
	"\x18UpdateOrderStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.tribecart.v1.OrderStatusR\x06status\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12'\n" +
	"\x0ftracking_number\x18\x04 \x01(\tR\x0etrackingNumber\x12\x18\n" +
	"\acarrier\x18\x05 \x01(\tR\acarrier\"c\n" +
	"\x12CancelOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0erefund_payment\x18\x03 \x01(\bR\rrefundPayment\"\x8e\x02\n" +
	"\x16GetOrderHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.tribecart.v1.OrderStatusR\x06status\x127\n" +
	"\tfrom_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate*\xe8\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17ORDER_STATUS_PROCESSING\x10\x02\x12\x18\n" +
	"\x14ORDER_STATUS_SHIPPED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x05\x12\x19\n" +
	"\x15ORDER_STATUS_REFUNDED\x10\x06\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\a*\xbe\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_METHOD_DEBIT_CARD\x10\x02\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_NET_BANKING\x10\x03\x12\x16\n" +
	"\x12PAYMENT_METHOD_UPI\x10\x04\x12\x16\n" +
	"\x12PAYMENT_METHOD_COD\x10\x052\xdb\x03\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12 .tribecart.v1.CreateOrderRequest\x1a\x13.tribecart.v1.Order\x12>\n" +
	"\bGetOrder\x12\x1d.tribecart.v1.GetOrderRequest\x1a\x13.tribecart.v1.Order\x12O\n" +
	"\n" +
	"ListOrders\x12\x1f.tribecart.v1.ListOrdersRequest\x1a .tribecart.v1.ListOrdersResponse\x12P\n" +
	"\x11UpdateOrderStatus\x12&.tribecart.v1.UpdateOrderStatusRequest\x1a\x13.tribecart.v1.Order\x12G\n" +
	"\vCancelOrder\x12 .tribecart.v1.CancelOrderRequest\x1a\x16.google.protobuf.Empty\x12Y\n" +
	"\x0fGetOrderHistory\x12$.tribecart.v1.GetOrderHistoryRequest\x1a .tribecart.v1.ListOrdersResponseB,Z*github.com/tribecart/proto/tribecart/v1;v1b\x06proto3"

var (
	file_tribecart_v1_orders_proto_rawDescOnce sync.Once
	file_tribecart_v1_orders_proto_rawDescData []byte
)

func file_tribecart_v1_orders_proto_rawDescGZIP() []byte {
	file_tribecart_v1_orders_proto_rawDescOnce.Do(func() {
		file_tribecart_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tribecart_v1_orders_proto_rawDesc), len(file_tribecart_v1_orders_proto_rawDesc)))
	})
	return file_tribecart_v1_orders_proto_rawDescData
}

var file_tribecart_v1_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tribecart_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_tribecart_v1_orders_proto_goTypes = []any{
	(OrderStatus)(0),                 // 0: tribecart.v1.OrderStatus
	(PaymentMethod)(0),               // 1: tribecart.v1.PaymentMethod
	(*OrderItem)(nil),                // 2: tribecart.v1.OrderItem
	(*ShippingAddress)(nil),          // 3: tribecart.v1.ShippingAddress
	(*Order)(nil),                    // 4: tribecart.v1.Order
	(*CreateOrderRequest)(nil),       // 5: tribecart.v1.CreateOrderRequest
	(*GetOrderRequest)(nil),          // 6: tribecart.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),        // 7: tribecart.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),       // 8: tribecart.v1.ListOrdersResponse
	(*UpdateOrderStatusRequest)(nil), // 9: tribecart.v1.UpdateOrderStatusRequest
	(*CancelOrderRequest)(nil),       // 10: tribecart.v1.CancelOrderRequest
	(*GetOrderHistoryRequest)(nil),   // 11: tribecart.v1.GetOrderHistoryRequest
	nil,                              // 12: tribecart.v1.Order.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 14: google.protobuf.Empty
}
var file_tribecart_v1_orders_proto_depIdxs = []int32{
	2,  // 0: tribecart.v1.Order.items:type_name -> tribecart.v1.OrderItem
	0,  // 1: tribecart.v1.Order.status:type_name -> tribecart.v1.OrderStatus
	1,  // 2: tribecart.v1.Order.payment_method:type_name -> tribecart.v1.PaymentMethod
	3,  // 3: tribecart.v1.Order.shipping_address:type_name -> tribecart.v1.ShippingAddress
	13, // 4: tribecart.v1.Order.ordered_at:type_name -> google.protobuf.Timestamp
	13, // 5: tribecart.v1.Order.shipped_at:type_name -> google.protobuf.Timestamp
	13, // 6: tribecart.v1.Order.delivered_at:type_name -> google.protobuf.Timestamp
	13, // 7: tribecart.v1.Order.cancelled_at:type_name -> google.protobuf.Timestamp
	12, // 8: tribecart.v1.Order.metadata:type_name -> tribecart.v1.Order.MetadataEntry
	13, // 9: tribecart.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	13, // 10: tribecart.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 11: tribecart.v1.CreateOrderRequest.items:type_name -> tribecart.v1.OrderItem
	1,  // 12: tribecart.v1.CreateOrderRequest.payment_method:type_name -> tribecart.v1.PaymentMethod
	0,  // 13: tribecart.v1.ListOrdersRequest.status:type_name -> tribecart.v1.OrderStatus
	13, // 14: tribecart.v1.ListOrdersRequest.from_date:type_name -> google.protobuf.Timestamp
	13, // 15: tribecart.v1.ListOrdersRequest.to_date:type_name -> google.protobuf.Timestamp
	4,  // 16: tribecart.v1.ListOrdersResponse.orders:type_name -> tribecart.v1.Order
	0,  // 17: tribecart.v1.UpdateOrderStatusRequest.status:type_name -> tribecart.v1.OrderStatus
	0,  // 18: tribecart.v1.GetOrderHistoryRequest.status:type_name -> tribecart.v1.OrderStatus
	13, // 19: tribecart.v1.GetOrderHistoryRequest.from_date:type_name -> google.protobuf.Timestamp
	13, // 20: tribecart.v1.GetOrderHistoryRequest.to_date:type_name -> google.protobuf.Timestamp
	5,  // 21: tribecart.v1.OrderService.CreateOrder:input_type -> tribecart.v1.CreateOrderRequest
	6,  // 22: tribecart.v1.OrderService.GetOrder:input_type -> tribecart.v1.GetOrderRequest
	7,  // 23: tribecart.v1.OrderService.ListOrders:input_type -> tribecart.v1.ListOrdersRequest
	9,  // 24: tribecart.v1.OrderService.UpdateOrderStatus:input_type -> tribecart.v1.UpdateOrderStatusRequest
	10, // 25: tribecart.v1.OrderService.CancelOrder:input_type -> tribecart.v1.CancelOrderRequest
	11, // 26: tribecart.v1.OrderService.GetOrderHistory:input_type -> tribecart.v1.GetOrderHistoryRequest
	4,  // 27: tribecart.v1.OrderService.CreateOrder:output_type -> tribecart.v1.Order
	4,  // 28: tribecart.v1.OrderService.GetOrder:output_type -> tribecart.v1.Order
	8,  // 29: tribecart.v1.OrderService.ListOrders:output_type -> tribecart.v1.ListOrdersResponse
	4,  // 30: tribecart.v1.OrderService.UpdateOrderStatus:output_type -> tribecart.v1.Order
	14, // 31: tribecart.v1.OrderService.CancelOrder:output_type -> google.protobuf.Empty
	8,  // 32: tribecart.v1.OrderService.GetOrderHistory:output_type -> tribecart.v1.ListOrdersResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_tribecart_v1_orders_proto_init() }
func file_tribecart_v1_orders_proto_init() {
	if File_tribecart_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tribecart_v1_orders_proto_rawDesc), len(file_tribecart_v1_orders_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tribecart_v1_orders_proto_goTypes,
		DependencyIndexes: file_tribecart_v1_orders_proto_depIdxs,
		EnumInfos:         file_tribecart_v1_orders_proto_enumTypes,
		MessageInfos:      file_tribecart_v1_orders_proto_msgTypes,
	}.Build()
	File_tribecart_v1_orders_proto = out.File
	file_tribecart_v1_orders_proto_goTypes = nil
	file_tribecart_v1_orders_proto_depIdxs = nil
}
