// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: tribecart/v1/products.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product status enumeration
type ProductStatus int32

const (
	ProductStatus_PRODUCT_STATUS_UNSPECIFIED  ProductStatus = 0
	ProductStatus_PRODUCT_STATUS_DRAFT        ProductStatus = 1
	ProductStatus_PRODUCT_STATUS_ACTIVE       ProductStatus = 2
	ProductStatus_PRODUCT_STATUS_ARCHIVED     ProductStatus = 3
	ProductStatus_PRODUCT_STATUS_OUT_OF_STOCK ProductStatus = 4
	ProductStatus_PRODUCT_STATUS_DISCONTINUED ProductStatus = 5
)

// Enum value maps for ProductStatus.
var (
	ProductStatus_name = map[int32]string{
		0: "PRODUCT_STATUS_UNSPECIFIED",
		1: "PRODUCT_STATUS_DRAFT",
		2: "PRODUCT_STATUS_ACTIVE",
		3: "PRODUCT_STATUS_ARCHIVED",
		4: "PRODUCT_STATUS_OUT_OF_STOCK",
		5: "PRODUCT_STATUS_DISCONTINUED",
	}
	ProductStatus_value = map[string]int32{
		"PRODUCT_STATUS_UNSPECIFIED":  0,
		"PRODUCT_STATUS_DRAFT":        1,
		"PRODUCT_STATUS_ACTIVE":       2,
		"PRODUCT_STATUS_ARCHIVED":     3,
		"PRODUCT_STATUS_OUT_OF_STOCK": 4,
		"PRODUCT_STATUS_DISCONTINUED": 5,
	}
)

func (x ProductStatus) Enum() *ProductStatus {
	p := new(ProductStatus)
	*p = x
	return p
}

func (x ProductStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tribecart_v1_products_proto_enumTypes[0].Descriptor()
}

func (ProductStatus) Type() protoreflect.EnumType {
	return &file_tribecart_v1_products_proto_enumTypes[0]
}

func (x ProductStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductStatus.Descriptor instead.
func (ProductStatus) EnumDescriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{0}
}

// Product type enumeration
type ProductType int32

const (
	ProductType_PRODUCT_TYPE_UNSPECIFIED ProductType = 0
	ProductType_PRODUCT_TYPE_PHYSICAL    ProductType = 1
	ProductType_PRODUCT_TYPE_DIGITAL     ProductType = 2
	ProductType_PRODUCT_TYPE_SERVICE     ProductType = 3
)

// Enum value maps for ProductType.
var (
	ProductType_name = map[int32]string{
		0: "PRODUCT_TYPE_UNSPECIFIED",
		1: "PRODUCT_TYPE_PHYSICAL",
		2: "PRODUCT_TYPE_DIGITAL",
		3: "PRODUCT_TYPE_SERVICE",
	}
	ProductType_value = map[string]int32{
		"PRODUCT_TYPE_UNSPECIFIED": 0,
		"PRODUCT_TYPE_PHYSICAL":    1,
		"PRODUCT_TYPE_DIGITAL":     2,
		"PRODUCT_TYPE_SERVICE":     3,
	}
)

func (x ProductType) Enum() *ProductType {
	p := new(ProductType)
	*p = x
	return p
}

func (x ProductType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductType) Descriptor() protoreflect.EnumDescriptor {
	return file_tribecart_v1_products_proto_enumTypes[1].Descriptor()
}

func (ProductType) Type() protoreflect.EnumType {
	return &file_tribecart_v1_products_proto_enumTypes[1]
}

func (x ProductType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductType.Descriptor instead.
func (ProductType) EnumDescriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{1}
}

// Product represents a product in the system
type Product struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the product
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Seller ID who owns this product
	SellerId string `protobuf:"bytes,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	// Product name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Product description (can include HTML)
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Product SKU (Stock Keeping Unit)
	Sku string `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	// Product barcode (UPC, EAN, etc.)
	Barcode string `protobuf:"bytes,6,opt,name=barcode,proto3" json:"barcode,omitempty"`
	// Base price of the product
	Price float64 `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	// Sale price of the product (if on sale)
	SalePrice float64 `protobuf:"fixed64,8,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	// Cost price of the product
	CostPrice float64 `protobuf:"fixed64,9,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	// Current stock quantity
	StockQuantity int32 `protobuf:"varint,10,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	// Whether to track inventory for this product
	TrackInventory bool `protobuf:"varint,11,opt,name=track_inventory,json=trackInventory,proto3" json:"track_inventory,omitempty"`
	// Minimum stock level before restock notification
	MinStockLevel int32 `protobuf:"varint,12,opt,name=min_stock_level,json=minStockLevel,proto3" json:"min_stock_level,omitempty"`
	// Product weight in grams
	Weight float64 `protobuf:"fixed64,13,opt,name=weight,proto3" json:"weight,omitempty"`
	// Product length in centimeters
	Length float64 `protobuf:"fixed64,14,opt,name=length,proto3" json:"length,omitempty"`
	// Product width in centimeters
	Width float64 `protobuf:"fixed64,15,opt,name=width,proto3" json:"width,omitempty"`
	// Product height in centimeters
	Height float64 `protobuf:"fixed64,16,opt,name=height,proto3" json:"height,omitempty"`
	// Product type (physical, digital, service)
	Type ProductType `protobuf:"varint,17,opt,name=type,proto3,enum=tribecart.v1.ProductType" json:"type,omitempty"`
	// Product status
	Status ProductStatus `protobuf:"varint,18,opt,name=status,proto3,enum=tribecart.v1.ProductStatus" json:"status,omitempty"`
	// Whether the product is featured
	IsFeatured bool `protobuf:"varint,19,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	// Whether the product is visible in the store
	IsVisible bool `protobuf:"varint,20,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	// Whether the product requires shipping
	RequiresShipping bool `protobuf:"varint,21,opt,name=requires_shipping,json=requiresShipping,proto3" json:"requires_shipping,omitempty"`
	// Whether the product is taxable
	IsTaxable bool `protobuf:"varint,22,opt,name=is_taxable,json=isTaxable,proto3" json:"is_taxable,omitempty"`
	// Tax class ID
	TaxClassId string `protobuf:"bytes,23,opt,name=tax_class_id,json=taxClassId,proto3" json:"tax_class_id,omitempty"`
	// Product categories (comma-separated IDs)
	CategoryIds []string `protobuf:"bytes,24,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	// Product tags
	Tags []string `protobuf:"bytes,25,rep,name=tags,proto3" json:"tags,omitempty"`
	// Product images (URLs or paths)
	Images []string `protobuf:"bytes,26,rep,name=images,proto3" json:"images,omitempty"`
	// Product specifications (key-value pairs)
	Specifications map[string]string `protobuf:"bytes,27,rep,name=specifications,proto3" json:"specifications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// SEO title
	SeoTitle string `protobuf:"bytes,28,opt,name=seo_title,json=seoTitle,proto3" json:"seo_title,omitempty"`
	// SEO description
	SeoDescription string `protobuf:"bytes,29,opt,name=seo_description,json=seoDescription,proto3" json:"seo_description,omitempty"`
	// SEO keywords
	SeoKeywords string `protobuf:"bytes,30,opt,name=seo_keywords,json=seoKeywords,proto3" json:"seo_keywords,omitempty"`
	// Created timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated timestamp
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,32,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Deleted timestamp (for soft delete)
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,33,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// Additional metadata
	Metadata map[string]string `protobuf:"bytes,34,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Product variants (for variable products)
	Variants      []*ProductVariant `protobuf:"bytes,35,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_tribecart_v1_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetSalePrice() float64 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

func (x *Product) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *Product) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Product) GetTrackInventory() bool {
	if x != nil {
		return x.TrackInventory
	}
	return false
}

func (x *Product) GetMinStockLevel() int32 {
	if x != nil {
		return x.MinStockLevel
	}
	return 0
}

func (x *Product) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Product) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Product) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Product) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Product) GetType() ProductType {
	if x != nil {
		return x.Type
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (x *Product) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

func (x *Product) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *Product) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *Product) GetRequiresShipping() bool {
	if x != nil {
		return x.RequiresShipping
	}
	return false
}

func (x *Product) GetIsTaxable() bool {
	if x != nil {
		return x.IsTaxable
	}
	return false
}

func (x *Product) GetTaxClassId() string {
	if x != nil {
		return x.TaxClassId
	}
	return ""
}

func (x *Product) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetSpecifications() map[string]string {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *Product) GetSeoTitle() string {
	if x != nil {
		return x.SeoTitle
	}
	return ""
}

func (x *Product) GetSeoDescription() string {
	if x != nil {
		return x.SeoDescription
	}
	return ""
}

func (x *Product) GetSeoKeywords() string {
	if x != nil {
		return x.SeoKeywords
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Product) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Product) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

// ProductVariant represents a variant of a product
type ProductVariant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the variant
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Parent product ID
	ProductId string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// Variant SKU
	Sku string `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	// Variant barcode
	Barcode string `protobuf:"bytes,4,opt,name=barcode,proto3" json:"barcode,omitempty"`
	// Price adjustment (can be positive or negative)
	PriceAdjustment float64 `protobuf:"fixed64,5,opt,name=price_adjustment,json=priceAdjustment,proto3" json:"price_adjustment,omitempty"`
	// Current stock quantity
	StockQuantity int32 `protobuf:"varint,6,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	// Variant attributes (e.g., size: XL, color: Red)
	Attributes map[string]string `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Additional images specific to this variant
	Images []string `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	// Created timestamp
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated timestamp
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductVariant) Reset() {
	*x = ProductVariant{}
	mi := &file_tribecart_v1_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVariant) ProtoMessage() {}

func (x *ProductVariant) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVariant.ProtoReflect.Descriptor instead.
func (*ProductVariant) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{1}
}

func (x *ProductVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductVariant) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductVariant) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductVariant) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *ProductVariant) GetPriceAdjustment() float64 {
	if x != nil {
		return x.PriceAdjustment
	}
	return 0
}

func (x *ProductVariant) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *ProductVariant) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ProductVariant) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductVariant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductVariant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request to create a new product
type CreateProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required fields
	Name          string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity int32   `protobuf:"varint,4,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	// Optional fields
	SellerId         string            `protobuf:"bytes,5,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Sku              string            `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	Barcode          string            `protobuf:"bytes,7,opt,name=barcode,proto3" json:"barcode,omitempty"`
	SalePrice        float64           `protobuf:"fixed64,8,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	CostPrice        float64           `protobuf:"fixed64,9,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	TrackInventory   bool              `protobuf:"varint,10,opt,name=track_inventory,json=trackInventory,proto3" json:"track_inventory,omitempty"`
	MinStockLevel    int32             `protobuf:"varint,11,opt,name=min_stock_level,json=minStockLevel,proto3" json:"min_stock_level,omitempty"`
	Weight           float64           `protobuf:"fixed64,12,opt,name=weight,proto3" json:"weight,omitempty"`
	Length           float64           `protobuf:"fixed64,13,opt,name=length,proto3" json:"length,omitempty"`
	Width            float64           `protobuf:"fixed64,14,opt,name=width,proto3" json:"width,omitempty"`
	Height           float64           `protobuf:"fixed64,15,opt,name=height,proto3" json:"height,omitempty"`
	Type             ProductType       `protobuf:"varint,16,opt,name=type,proto3,enum=tribecart.v1.ProductType" json:"type,omitempty"`
	Status           ProductStatus     `protobuf:"varint,17,opt,name=status,proto3,enum=tribecart.v1.ProductStatus" json:"status,omitempty"`
	IsFeatured       bool              `protobuf:"varint,18,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	IsVisible        bool              `protobuf:"varint,19,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	RequiresShipping bool              `protobuf:"varint,20,opt,name=requires_shipping,json=requiresShipping,proto3" json:"requires_shipping,omitempty"`
	IsTaxable        bool              `protobuf:"varint,21,opt,name=is_taxable,json=isTaxable,proto3" json:"is_taxable,omitempty"`
	TaxClassId       string            `protobuf:"bytes,22,opt,name=tax_class_id,json=taxClassId,proto3" json:"tax_class_id,omitempty"`
	CategoryIds      []string          `protobuf:"bytes,23,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	Tags             []string          `protobuf:"bytes,24,rep,name=tags,proto3" json:"tags,omitempty"`
	Images           []string          `protobuf:"bytes,25,rep,name=images,proto3" json:"images,omitempty"`
	Specifications   map[string]string `protobuf:"bytes,26,rep,name=specifications,proto3" json:"specifications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SeoTitle         string            `protobuf:"bytes,27,opt,name=seo_title,json=seoTitle,proto3" json:"seo_title,omitempty"`
	SeoDescription   string            `protobuf:"bytes,28,opt,name=seo_description,json=seoDescription,proto3" json:"seo_description,omitempty"`
	SeoKeywords      string            `protobuf:"bytes,29,opt,name=seo_keywords,json=seoKeywords,proto3" json:"seo_keywords,omitempty"`
	Variants         []*ProductVariant `protobuf:"bytes,30,rep,name=variants,proto3" json:"variants,omitempty"`
	Metadata         map[string]string `protobuf:"bytes,31,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *CreateProductRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *CreateProductRequest) GetSalePrice() float64 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

func (x *CreateProductRequest) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *CreateProductRequest) GetTrackInventory() bool {
	if x != nil {
		return x.TrackInventory
	}
	return false
}

func (x *CreateProductRequest) GetMinStockLevel() int32 {
	if x != nil {
		return x.MinStockLevel
	}
	return 0
}

func (x *CreateProductRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateProductRequest) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CreateProductRequest) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateProductRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateProductRequest) GetType() ProductType {
	if x != nil {
		return x.Type
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (x *CreateProductRequest) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

func (x *CreateProductRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *CreateProductRequest) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *CreateProductRequest) GetRequiresShipping() bool {
	if x != nil {
		return x.RequiresShipping
	}
	return false
}

func (x *CreateProductRequest) GetIsTaxable() bool {
	if x != nil {
		return x.IsTaxable
	}
	return false
}

func (x *CreateProductRequest) GetTaxClassId() string {
	if x != nil {
		return x.TaxClassId
	}
	return ""
}

func (x *CreateProductRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *CreateProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateProductRequest) GetSpecifications() map[string]string {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *CreateProductRequest) GetSeoTitle() string {
	if x != nil {
		return x.SeoTitle
	}
	return ""
}

func (x *CreateProductRequest) GetSeoDescription() string {
	if x != nil {
		return x.SeoDescription
	}
	return ""
}

func (x *CreateProductRequest) GetSeoKeywords() string {
	if x != nil {
		return x.SeoKeywords
	}
	return ""
}

func (x *CreateProductRequest) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *CreateProductRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request to get a product
type GetProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Product ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Whether to include variants in the response
	IncludeVariants bool `protobuf:"varint,2,opt,name=include_variants,json=includeVariants,proto3" json:"include_variants,omitempty"`
	// Whether to include deleted products
	IncludeDeleted bool `protobuf:"varint,3,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetProductRequest) GetIncludeVariants() bool {
	if x != nil {
		return x.IncludeVariants
	}
	return false
}

func (x *GetProductRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

// Request to update a product
type UpdateProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required fields
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Update mask to specify which fields to update
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Fields that can be updated
	Name             string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string            `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price            float64           `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity    int32             `protobuf:"varint,6,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Sku              string            `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`
	Barcode          string            `protobuf:"bytes,8,opt,name=barcode,proto3" json:"barcode,omitempty"`
	SalePrice        float64           `protobuf:"fixed64,9,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	CostPrice        float64           `protobuf:"fixed64,10,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	TrackInventory   bool              `protobuf:"varint,11,opt,name=track_inventory,json=trackInventory,proto3" json:"track_inventory,omitempty"`
	MinStockLevel    int32             `protobuf:"varint,12,opt,name=min_stock_level,json=minStockLevel,proto3" json:"min_stock_level,omitempty"`
	Weight           float64           `protobuf:"fixed64,13,opt,name=weight,proto3" json:"weight,omitempty"`
	Length           float64           `protobuf:"fixed64,14,opt,name=length,proto3" json:"length,omitempty"`
	Width            float64           `protobuf:"fixed64,15,opt,name=width,proto3" json:"width,omitempty"`
	Height           float64           `protobuf:"fixed64,16,opt,name=height,proto3" json:"height,omitempty"`
	Type             ProductType       `protobuf:"varint,17,opt,name=type,proto3,enum=tribecart.v1.ProductType" json:"type,omitempty"`
	Status           ProductStatus     `protobuf:"varint,18,opt,name=status,proto3,enum=tribecart.v1.ProductStatus" json:"status,omitempty"`
	IsFeatured       bool              `protobuf:"varint,19,opt,name=is_featured,json=isFeatured,proto3" json:"is_featured,omitempty"`
	IsVisible        bool              `protobuf:"varint,20,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	RequiresShipping bool              `protobuf:"varint,21,opt,name=requires_shipping,json=requiresShipping,proto3" json:"requires_shipping,omitempty"`
	IsTaxable        bool              `protobuf:"varint,22,opt,name=is_taxable,json=isTaxable,proto3" json:"is_taxable,omitempty"`
	TaxClassId       string            `protobuf:"bytes,23,opt,name=tax_class_id,json=taxClassId,proto3" json:"tax_class_id,omitempty"`
	CategoryIds      []string          `protobuf:"bytes,24,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	Tags             []string          `protobuf:"bytes,25,rep,name=tags,proto3" json:"tags,omitempty"`
	Images           []string          `protobuf:"bytes,26,rep,name=images,proto3" json:"images,omitempty"`
	Specifications   map[string]string `protobuf:"bytes,27,rep,name=specifications,proto3" json:"specifications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SeoTitle         string            `protobuf:"bytes,28,opt,name=seo_title,json=seoTitle,proto3" json:"seo_title,omitempty"`
	SeoDescription   string            `protobuf:"bytes,29,opt,name=seo_description,json=seoDescription,proto3" json:"seo_description,omitempty"`
	SeoKeywords      string            `protobuf:"bytes,30,opt,name=seo_keywords,json=seoKeywords,proto3" json:"seo_keywords,omitempty"`
	Variants         []*ProductVariant `protobuf:"bytes,31,rep,name=variants,proto3" json:"variants,omitempty"`
	Metadata         map[string]string `protobuf:"bytes,32,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *UpdateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *UpdateProductRequest) GetSalePrice() float64 {
	if x != nil {
		return x.SalePrice
	}
	return 0
}

func (x *UpdateProductRequest) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *UpdateProductRequest) GetTrackInventory() bool {
	if x != nil {
		return x.TrackInventory
	}
	return false
}

func (x *UpdateProductRequest) GetMinStockLevel() int32 {
	if x != nil {
		return x.MinStockLevel
	}
	return 0
}

func (x *UpdateProductRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateProductRequest) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *UpdateProductRequest) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UpdateProductRequest) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UpdateProductRequest) GetType() ProductType {
	if x != nil {
		return x.Type
	}
	return ProductType_PRODUCT_TYPE_UNSPECIFIED
}

func (x *UpdateProductRequest) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

func (x *UpdateProductRequest) GetIsFeatured() bool {
	if x != nil {
		return x.IsFeatured
	}
	return false
}

func (x *UpdateProductRequest) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *UpdateProductRequest) GetRequiresShipping() bool {
	if x != nil {
		return x.RequiresShipping
	}
	return false
}

func (x *UpdateProductRequest) GetIsTaxable() bool {
	if x != nil {
		return x.IsTaxable
	}
	return false
}

func (x *UpdateProductRequest) GetTaxClassId() string {
	if x != nil {
		return x.TaxClassId
	}
	return ""
}

func (x *UpdateProductRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *UpdateProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateProductRequest) GetSpecifications() map[string]string {
	if x != nil {
		return x.Specifications
	}
	return nil
}

func (x *UpdateProductRequest) GetSeoTitle() string {
	if x != nil {
		return x.SeoTitle
	}
	return ""
}

func (x *UpdateProductRequest) GetSeoDescription() string {
	if x != nil {
		return x.SeoDescription
	}
	return ""
}

func (x *UpdateProductRequest) GetSeoKeywords() string {
	if x != nil {
		return x.SeoKeywords
	}
	return ""
}

func (x *UpdateProductRequest) GetVariants() []*ProductVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *UpdateProductRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Request to delete a product
type DeleteProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Product ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Whether to perform a hard delete (permanent)
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteProductRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Request to list products with filtering and pagination
type ListProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination
	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Filtering
	SellerId    string        `protobuf:"bytes,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	CategoryIds []string      `protobuf:"bytes,4,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	MinPrice    float64       `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice    float64       `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Status      ProductStatus `protobuf:"varint,7,opt,name=status,proto3,enum=tribecart.v1.ProductStatus" json:"status,omitempty"`
	InStock     bool          `protobuf:"varint,8,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	Featured    bool          `protobuf:"varint,9,opt,name=featured,proto3" json:"featured,omitempty"`
	SearchQuery string        `protobuf:"bytes,10,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	// Sorting
	SortBy string `protobuf:"bytes,11,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"` // e.g., "price", "-price", "name", "-name"
	// Whether to include deleted products
	IncludeDeleted bool `protobuf:"varint,12,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *ListProductsRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *ListProductsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ListProductsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ListProductsRequest) GetStatus() ProductStatus {
	if x != nil {
		return x.Status
	}
	return ProductStatus_PRODUCT_STATUS_UNSPECIFIED
}

func (x *ListProductsRequest) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *ListProductsRequest) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *ListProductsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *ListProductsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListProductsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

// Response containing a list of products
type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_tribecart_v1_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Request to update product stock
type UpdateStockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Product ID
	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// Variant ID (for variable products)
	VariantId string `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	// Quantity to add (positive) or remove (negative)
	Quantity int32 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Reason for stock update (e.g., "sale", "restock", "adjustment")
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional reference ID (e.g., order ID for sales)
	ReferenceId   string `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateStockRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateStockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateStockRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

// Request to search products
type SearchProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search query
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Pagination
	Page     int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Filtering
	CategoryIds []string `protobuf:"bytes,4,rep,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	MinPrice    float64  `protobuf:"fixed64,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice    float64  `protobuf:"fixed64,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	// Whether to include product variants in search
	IncludeVariants bool `protobuf:"varint,7,opt,name=include_variants,json=includeVariants,proto3" json:"include_variants,omitempty"`
	// Whether to include out of stock products
	IncludeOutOfStock bool `protobuf:"varint,8,opt,name=include_out_of_stock,json=includeOutOfStock,proto3" json:"include_out_of_stock,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{9}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchProductsRequest) GetCategoryIds() []string {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *SearchProductsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchProductsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchProductsRequest) GetIncludeVariants() bool {
	if x != nil {
		return x.IncludeVariants
	}
	return false
}

func (x *SearchProductsRequest) GetIncludeOutOfStock() bool {
	if x != nil {
		return x.IncludeOutOfStock
	}
	return false
}

// Response containing search results
type SearchProductsResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Products   []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	TotalCount int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page       int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize   int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Aggregations/facets for search results
	Aggregations  map[string]*SearchAggregation `protobuf:"bytes,5,rep,name=aggregations,proto3" json:"aggregations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_tribecart_v1_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{10}
}

func (x *SearchProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *SearchProductsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchProductsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchProductsResponse) GetAggregations() map[string]*SearchAggregation {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

// Search aggregation/facet information
type SearchAggregation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Aggregation buckets
	Buckets []*AggregationBucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	// Total number of unique values
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAggregation) Reset() {
	*x = SearchAggregation{}
	mi := &file_tribecart_v1_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAggregation) ProtoMessage() {}

func (x *SearchAggregation) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAggregation.ProtoReflect.Descriptor instead.
func (*SearchAggregation) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{11}
}

func (x *SearchAggregation) GetBuckets() []*AggregationBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *SearchAggregation) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Aggregation bucket for search facets
type AggregationBucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket key (e.g., category ID, price range)
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Number of documents in this bucket
	DocCount int32 `protobuf:"varint,2,opt,name=doc_count,json=docCount,proto3" json:"doc_count,omitempty"`
	// Optional display name
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// Optional min value (for numeric ranges)
	Min float64 `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	// Optional max value (for numeric ranges)
	Max           float64 `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationBucket) Reset() {
	*x = AggregationBucket{}
	mi := &file_tribecart_v1_products_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationBucket) ProtoMessage() {}

func (x *AggregationBucket) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationBucket.ProtoReflect.Descriptor instead.
func (*AggregationBucket) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{12}
}

func (x *AggregationBucket) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AggregationBucket) GetDocCount() int32 {
	if x != nil {
		return x.DocCount
	}
	return 0
}

func (x *AggregationBucket) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AggregationBucket) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *AggregationBucket) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// Request to get products by category
type GetProductsByCategoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Category ID
	CategoryId string `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// Whether to include subcategories
	IncludeSubcategories bool `protobuf:"varint,2,opt,name=include_subcategories,json=includeSubcategories,proto3" json:"include_subcategories,omitempty"`
	// Pagination
	Page     int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Sorting
	SortBy        string `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByCategoryRequest) Reset() {
	*x = GetProductsByCategoryRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByCategoryRequest) ProtoMessage() {}

func (x *GetProductsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{13}
}

func (x *GetProductsByCategoryRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetProductsByCategoryRequest) GetIncludeSubcategories() bool {
	if x != nil {
		return x.IncludeSubcategories
	}
	return false
}

func (x *GetProductsByCategoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProductsByCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetProductsByCategoryRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

// Request to bulk import products
type BulkImportProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Import format (e.g., "json", "csv")
	Format string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	// Base64-encoded file content
	FileContent []byte `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	// Import options
	Options *ImportOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	// Callback URL for import completion notification
	CallbackUrl   string `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkImportProductsRequest) Reset() {
	*x = BulkImportProductsRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportProductsRequest) ProtoMessage() {}

func (x *BulkImportProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportProductsRequest.ProtoReflect.Descriptor instead.
func (*BulkImportProductsRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{14}
}

func (x *BulkImportProductsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *BulkImportProductsRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *BulkImportProductsRequest) GetOptions() *ImportOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *BulkImportProductsRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

// Import options for bulk operations
type ImportOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to update existing products
	UpdateExisting bool `protobuf:"varint,1,opt,name=update_existing,json=updateExisting,proto3" json:"update_existing,omitempty"`
	// Whether to create new products if they don't exist
	CreateNew bool `protobuf:"varint,2,opt,name=create_new,json=createNew,proto3" json:"create_new,omitempty"`
	// Whether to delete products not in the import file
	DeleteMissing bool `protobuf:"varint,3,opt,name=delete_missing,json=deleteMissing,proto3" json:"delete_missing,omitempty"`
	// Field mappings (for CSV)
	FieldMappings map[string]string `protobuf:"bytes,4,rep,name=field_mappings,json=fieldMappings,proto3" json:"field_mappings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Default values for fields not in import
	DefaultValues map[string]string `protobuf:"bytes,5,rep,name=default_values,json=defaultValues,proto3" json:"default_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportOptions) Reset() {
	*x = ImportOptions{}
	mi := &file_tribecart_v1_products_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportOptions) ProtoMessage() {}

func (x *ImportOptions) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportOptions.ProtoReflect.Descriptor instead.
func (*ImportOptions) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{15}
}

func (x *ImportOptions) GetUpdateExisting() bool {
	if x != nil {
		return x.UpdateExisting
	}
	return false
}

func (x *ImportOptions) GetCreateNew() bool {
	if x != nil {
		return x.CreateNew
	}
	return false
}

func (x *ImportOptions) GetDeleteMissing() bool {
	if x != nil {
		return x.DeleteMissing
	}
	return false
}

func (x *ImportOptions) GetFieldMappings() map[string]string {
	if x != nil {
		return x.FieldMappings
	}
	return nil
}

func (x *ImportOptions) GetDefaultValues() map[string]string {
	if x != nil {
		return x.DefaultValues
	}
	return nil
}

// Response for bulk import
type BulkImportProductsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Import job ID
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Total number of records processed
	TotalRecords int32 `protobuf:"varint,2,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	// Number of successful imports
	SuccessCount int32 `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// Number of failed imports
	ErrorCount int32 `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	// Error details (if any)
	Errors []*ImportError `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	// Import status
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Timestamp when import started
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Timestamp when import completed
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkImportProductsResponse) Reset() {
	*x = BulkImportProductsResponse{}
	mi := &file_tribecart_v1_products_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportProductsResponse) ProtoMessage() {}

func (x *BulkImportProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportProductsResponse.ProtoReflect.Descriptor instead.
func (*BulkImportProductsResponse) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{16}
}

func (x *BulkImportProductsResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BulkImportProductsResponse) GetTotalRecords() int32 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

func (x *BulkImportProductsResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkImportProductsResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *BulkImportProductsResponse) GetErrors() []*ImportError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BulkImportProductsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BulkImportProductsResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *BulkImportProductsResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// Import error details
type ImportError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Row/record number
	Row int32 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	// Field with error
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	// Error message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Error code
	Code string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	// Raw data that caused the error
	RawData       string `protobuf:"bytes,5,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportError) Reset() {
	*x = ImportError{}
	mi := &file_tribecart_v1_products_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportError) ProtoMessage() {}

func (x *ImportError) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportError.ProtoReflect.Descriptor instead.
func (*ImportError) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{17}
}

func (x *ImportError) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ImportError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ImportError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ImportError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ImportError) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

// Request to bulk export products
type BulkExportProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Export format (e.g., "json", "csv")
	Format string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	// Filter criteria
	Filter *ListProductsRequest `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	// Fields to include in export
	Fields []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Callback URL for export completion notification
	CallbackUrl   string `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkExportProductsRequest) Reset() {
	*x = BulkExportProductsRequest{}
	mi := &file_tribecart_v1_products_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkExportProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkExportProductsRequest) ProtoMessage() {}

func (x *BulkExportProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkExportProductsRequest.ProtoReflect.Descriptor instead.
func (*BulkExportProductsRequest) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{18}
}

func (x *BulkExportProductsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *BulkExportProductsRequest) GetFilter() *ListProductsRequest {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *BulkExportProductsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *BulkExportProductsRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

// Response for bulk export
type BulkExportProductsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Export job ID
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// URL to download the exported file (when complete)
	DownloadUrl string `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	// Export status
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Number of records exported
	RecordCount int32 `protobuf:"varint,4,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	// Timestamp when export started
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Timestamp when export completed
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkExportProductsResponse) Reset() {
	*x = BulkExportProductsResponse{}
	mi := &file_tribecart_v1_products_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkExportProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkExportProductsResponse) ProtoMessage() {}

func (x *BulkExportProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tribecart_v1_products_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkExportProductsResponse.ProtoReflect.Descriptor instead.
func (*BulkExportProductsResponse) Descriptor() ([]byte, []int) {
	return file_tribecart_v1_products_proto_rawDescGZIP(), []int{19}
}

func (x *BulkExportProductsResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BulkExportProductsResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *BulkExportProductsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BulkExportProductsResponse) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *BulkExportProductsResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *BulkExportProductsResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_tribecart_v1_products_proto protoreflect.FileDescriptor

const file_tribecart_v1_products_proto_rawDesc = "" +
	"\n" +
	"\x1btribecart/v1/products.proto\x12\ftribecart.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"\x8b\v\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\tR\bsellerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\x06 \x01(\tR\abarcode\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"sale_price\x18\b \x01(\x01R\tsalePrice\x12\x1d\n" +
	"\n" +
	"cost_price\x18\t \x01(\x01R\tcostPrice\x12%\n" +
	"\x0estock_quantity\x18\n" +
	" \x01(\x05R\rstockQuantity\x12'\n" +
	"\x0ftrack_inventory\x18\v \x01(\bR\x0etrackInventory\x12&\n" +
	"\x0fmin_stock_level\x18\f \x01(\x05R\rminStockLevel\x12\x16\n" +
	"\x06weight\x18\r \x01(\x01R\x06weight\x12\x16\n" +
	"\x06length\x18\x0e \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x0f \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x10 \x01(\x01R\x06height\x12-\n" +
	"\x04type\x18\x11 \x01(\x0e2\x19.tribecart.v1.ProductTypeR\x04type\x123\n" +
	"\x06status\x18\x12 \x01(\x0e2\x1b.tribecart.v1.ProductStatusR\x06status\x12\x1f\n" +
	"\vis_featured\x18\x13 \x01(\bR\n" +
	"isFeatured\x12\x1d\n" +
	"\n" +
	"is_visible\x18\x14 \x01(\bR\tisVisible\x12+\n" +
	"\x11requires_shipping\x18\x15 \x01(\bR\x10requiresShipping\x12\x1d\n" +
	"\n" +
	"is_taxable\x18\x16 \x01(\bR\tisTaxable\x12 \n" +
	"\ftax_class_id\x18\x17 \x01(\tR\n" +
	"taxClassId\x12!\n" +
	"\fcategory_ids\x18\x18 \x03(\tR\vcategoryIds\x12\x12\n" +
	"\x04tags\x18\x19 \x03(\tR\x04tags\x12\x16\n" +
	"\x06images\x18\x1a \x03(\tR\x06images\x12Q\n" +
	"\x0especifications\x18\x1b \x03(\v2).tribecart.v1.Product.SpecificationsEntryR\x0especifications\x12\x1b\n" +
	"\tseo_title\x18\x1c \x01(\tR\bseoTitle\x12'\n" +
	"\x0fseo_description\x18\x1d \x01(\tR\x0eseoDescription\x12!\n" +
	"\fseo_keywords\x18\x1e \x01(\tR\vseoKeywords\x129\n" +
	"\n" +
	"created_at\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18  \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18! \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12?\n" +
	"\bmetadata\x18\" \x03(\v2#.tribecart.v1.Product.MetadataEntryR\bmetadata\x128\n" +
	"\bvariants\x18# \x03(\v2\x1c.tribecart.v1.ProductVariantR\bvariants\x1aA\n" +
	"\x13SpecificationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x03\n" +
	"\x0eProductVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\x04 \x01(\tR\abarcode\x12)\n" +
	"\x10price_adjustment\x18\x05 \x01(\x01R\x0fpriceAdjustment\x12%\n" +
	"\x0estock_quantity\x18\x06 \x01(\x05R\rstockQuantity\x12L\n" +
	"\n" +
	"attributes\x18\a \x03(\v2,.tribecart.v1.ProductVariant.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\t\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x04 \x01(\x05R\rstockQuantity\x12\x1b\n" +
	"\tseller_id\x18\x05 \x01(\tR\bsellerId\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\a \x01(\tR\abarcode\x12\x1d\n" +
	"\n" +
	"sale_price\x18\b \x01(\x01R\tsalePrice\x12\x1d\n" +
	"\n" +
	"cost_price\x18\t \x01(\x01R\tcostPrice\x12'\n" +
	"\x0ftrack_inventory\x18\n" +
	" \x01(\bR\x0etrackInventory\x12&\n" +
	"\x0fmin_stock_level\x18\v \x01(\x05R\rminStockLevel\x12\x16\n" +
	"\x06weight\x18\f \x01(\x01R\x06weight\x12\x16\n" +
	"\x06length\x18\r \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x0e \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x0f \x01(\x01R\x06height\x12-\n" +
	"\x04type\x18\x10 \x01(\x0e2\x19.tribecart.v1.ProductTypeR\x04type\x123\n" +
	"\x06status\x18\x11 \x01(\x0e2\x1b.tribecart.v1.ProductStatusR\x06status\x12\x1f\n" +
	"\vis_featured\x18\x12 \x01(\bR\n" +
	"isFeatured\x12\x1d\n" +
	"\n" +
	"is_visible\x18\x13 \x01(\bR\tisVisible\x12+\n" +
	"\x11requires_shipping\x18\x14 \x01(\bR\x10requiresShipping\x12\x1d\n" +
	"\n" +
	"is_taxable\x18\x15 \x01(\bR\tisTaxable\x12 \n" +
	"\ftax_class_id\x18\x16 \x01(\tR\n" +
	"taxClassId\x12!\n" +
	"\fcategory_ids\x18\x17 \x03(\tR\vcategoryIds\x12\x12\n" +
	"\x04tags\x18\x18 \x03(\tR\x04tags\x12\x16\n" +
	"\x06images\x18\x19 \x03(\tR\x06images\x12^\n" +
	"\x0especifications\x18\x1a \x03(\v26.tribecart.v1.CreateProductRequest.SpecificationsEntryR\x0especifications\x12\x1b\n" +
	"\tseo_title\x18\x1b \x01(\tR\bseoTitle\x12'\n" +
	"\x0fseo_description\x18\x1c \x01(\tR\x0eseoDescription\x12!\n" +
	"\fseo_keywords\x18\x1d \x01(\tR\vseoKeywords\x128\n" +
	"\bvariants\x18\x1e \x03(\v2\x1c.tribecart.v1.ProductVariantR\bvariants\x12L\n" +
	"\bmetadata\x18\x1f \x03(\v20.tribecart.v1.CreateProductRequest.MetadataEntryR\bmetadata\x1aA\n" +
	"\x13SpecificationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10include_variants\x18\x02 \x01(\bR\x0fincludeVariants\x12'\n" +
	"\x0finclude_deleted\x18\x03 \x01(\bR\x0eincludeDeleted\"\xa1\n" +
	"\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x06 \x01(\x05R\rstockQuantity\x12\x10\n" +
	"\x03sku\x18\a \x01(\tR\x03sku\x12\x18\n" +
	"\abarcode\x18\b \x01(\tR\abarcode\x12\x1d\n" +
	"\n" +
	"sale_price\x18\t \x01(\x01R\tsalePrice\x12\x1d\n" +
	"\n" +
	"cost_price\x18\n" +
	" \x01(\x01R\tcostPrice\x12'\n" +
	"\x0ftrack_inventory\x18\v \x01(\bR\x0etrackInventory\x12&\n" +
	"\x0fmin_stock_level\x18\f \x01(\x05R\rminStockLevel\x12\x16\n" +
	"\x06weight\x18\r \x01(\x01R\x06weight\x12\x16\n" +
	"\x06length\x18\x0e \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x0f \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x10 \x01(\x01R\x06height\x12-\n" +
	"\x04type\x18\x11 \x01(\x0e2\x19.tribecart.v1.ProductTypeR\x04type\x123\n" +
	"\x06status\x18\x12 \x01(\x0e2\x1b.tribecart.v1.ProductStatusR\x06status\x12\x1f\n" +
	"\vis_featured\x18\x13 \x01(\bR\n" +
	"isFeatured\x12\x1d\n" +
	"\n" +
	"is_visible\x18\x14 \x01(\bR\tisVisible\x12+\n" +
	"\x11requires_shipping\x18\x15 \x01(\bR\x10requiresShipping\x12\x1d\n" +
	"\n" +
	"is_taxable\x18\x16 \x01(\bR\tisTaxable\x12 \n" +
	"\ftax_class_id\x18\x17 \x01(\tR\n" +
	"taxClassId\x12!\n" +
	"\fcategory_ids\x18\x18 \x03(\tR\vcategoryIds\x12\x12\n" +
	"\x04tags\x18\x19 \x03(\tR\x04tags\x12\x16\n" +
	"\x06images\x18\x1a \x03(\tR\x06images\x12^\n" +
	"\x0especifications\x18\x1b \x03(\v26.tribecart.v1.UpdateProductRequest.SpecificationsEntryR\x0especifications\x12\x1b\n" +
	"\tseo_title\x18\x1c \x01(\tR\bseoTitle\x12'\n" +
	"\x0fseo_description\x18\x1d \x01(\tR\x0eseoDescription\x12!\n" +
	"\fseo_keywords\x18\x1e \x01(\tR\vseoKeywords\x128\n" +
	"\bvariants\x18\x1f \x03(\v2\x1c.tribecart.v1.ProductVariantR\bvariants\x12L\n" +
	"\bmetadata\x18  \x03(\v20.tribecart.v1.UpdateProductRequest.MetadataEntryR\bmetadata\x1aA\n" +
	"\x13SpecificationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x91\x03\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\tR\bsellerId\x12!\n" +
	"\fcategory_ids\x18\x04 \x03(\tR\vcategoryIds\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x01R\bmaxPrice\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.tribecart.v1.ProductStatusR\x06status\x12\x19\n" +
	"\bin_stock\x18\b \x01(\bR\ainStock\x12\x1a\n" +
	"\bfeatured\x18\t \x01(\bR\bfeatured\x12!\n" +
	"\fsearch_query\x18\n" +
	" \x01(\tR\vsearchQuery\x12\x17\n" +
	"\asort_by\x18\v \x01(\tR\x06sortBy\x12'\n" +
	"\x0finclude_deleted\x18\f \x01(\bR\x0eincludeDeleted\"\x9b\x01\n" +
	"\x14ListProductsResponse\x121\n" +
	"\bproducts\x18\x01 \x03(\v2\x15.tribecart.v1.ProductR\bproducts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa9\x01\n" +
	"\x12UpdateStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\"\x97\x02\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12!\n" +
	"\fcategory_ids\x18\x04 \x03(\tR\vcategoryIds\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x01R\bmaxPrice\x12)\n" +
	"\x10include_variants\x18\a \x01(\bR\x0fincludeVariants\x12/\n" +
	"\x14include_out_of_stock\x18\b \x01(\bR\x11includeOutOfStock\"\xdb\x02\n" +
	"\x16SearchProductsResponse\x121\n" +
	"\bproducts\x18\x01 \x03(\v2\x15.tribecart.v1.ProductR\bproducts\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12Z\n" +
	"\faggregations\x18\x05 \x03(\v26.tribecart.v1.SearchProductsResponse.AggregationsEntryR\faggregations\x1a`\n" +
	"\x11AggregationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.tribecart.v1.SearchAggregationR\x05value:\x028\x01\"d\n" +
	"\x11SearchAggregation\x129\n" +
	"\abuckets\x18\x01 \x03(\v2\x1f.tribecart.v1.AggregationBucketR\abuckets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"|\n" +
	"\x11AggregationBucket\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tdoc_count\x18\x02 \x01(\x05R\bdocCount\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x10\n" +
	"\x03min\x18\x04 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x05 \x01(\x01R\x03max\"\xbe\x01\n" +
	"\x1cGetProductsByCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x123\n" +
	"\x15include_subcategories\x18\x02 \x01(\bR\x14includeSubcategories\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\"\xb0\x01\n" +
	"\x19BulkImportProductsRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\x125\n" +
	"\aoptions\x18\x03 \x01(\v2\x1b.tribecart.v1.ImportOptionsR\aoptions\x12!\n" +
	"\fcallback_url\x18\x04 \x01(\tR\vcallbackUrl\"\xb0\x03\n" +
	"\rImportOptions\x12'\n" +
	"\x0fupdate_existing\x18\x01 \x01(\bR\x0eupdateExisting\x12\x1d\n" +
	"\n" +
	"create_new\x18\x02 \x01(\bR\tcreateNew\x12%\n" +
	"\x0edelete_missing\x18\x03 \x01(\bR\rdeleteMissing\x12U\n" +
	"\x0efield_mappings\x18\x04 \x03(\v2..tribecart.v1.ImportOptions.FieldMappingsEntryR\rfieldMappings\x12U\n" +
	"\x0edefault_values\x18\x05 \x03(\v2..tribecart.v1.ImportOptions.DefaultValuesEntryR\rdefaultValues\x1a@\n" +
	"\x12FieldMappingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12DefaultValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x02\n" +
	"\x1aBulkImportProductsResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rtotal_records\x18\x02 \x01(\x05R\ftotalRecords\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x05R\n" +
	"errorCount\x121\n" +
	"\x06errors\x18\x05 \x03(\v2\x19.tribecart.v1.ImportErrorR\x06errors\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"~\n" +
	"\vImportError\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x19\n" +
	"\braw_data\x18\x05 \x01(\tR\arawData\"\xa9\x01\n" +
	"\x19BulkExportProductsRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x129\n" +
	"\x06filter\x18\x02 \x01(\v2!.tribecart.v1.ListProductsRequestR\x06filter\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12!\n" +
	"\fcallback_url\x18\x04 \x01(\tR\vcallbackUrl\"\x8b\x02\n" +
	"\x1aBulkExportProductsResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\frecord_count\x18\x04 \x01(\x05R\vrecordCount\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt*\xc3\x01\n" +
	"\rProductStatus\x12\x1e\n" +
	"\x1aPRODUCT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PRODUCT_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15PRODUCT_STATUS_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17PRODUCT_STATUS_ARCHIVED\x10\x03\x12\x1f\n" +
	"\x1bPRODUCT_STATUS_OUT_OF_STOCK\x10\x04\x12\x1f\n" +
	"\x1bPRODUCT_STATUS_DISCONTINUED\x10\x05*z\n" +
	"\vProductType\x12\x1c\n" +
	"\x18PRODUCT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PRODUCT_TYPE_PHYSICAL\x10\x01\x12\x18\n" +
	"\x14PRODUCT_TYPE_DIGITAL\x10\x02\x12\x18\n" +
	"\x14PRODUCT_TYPE_SERVICE\x10\x032\xf2\x06\n" +
	"\x0eProductService\x12J\n" +
	"\rCreateProduct\x12\".tribecart.v1.CreateProductRequest\x1a\x15.tribecart.v1.Product\x12D\n" +
	"\n" +
	"GetProduct\x12\x1f.tribecart.v1.GetProductRequest\x1a\x15.tribecart.v1.Product\x12J\n" +
	"\rUpdateProduct\x12\".tribecart.v1.UpdateProductRequest\x1a\x15.tribecart.v1.Product\x12K\n" +
	"\rDeleteProduct\x12\".tribecart.v1.DeleteProductRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\fListProducts\x12!.tribecart.v1.ListProductsRequest\x1a\".tribecart.v1.ListProductsResponse\x12F\n" +
	"\vUpdateStock\x12 .tribecart.v1.UpdateStockRequest\x1a\x15.tribecart.v1.Product\x12[\n" +
	"\x0eSearchProducts\x12#.tribecart.v1.SearchProductsRequest\x1a$.tribecart.v1.SearchProductsResponse\x12g\n" +
	"\x15GetProductsByCategory\x12*.tribecart.v1.GetProductsByCategoryRequest\x1a\".tribecart.v1.ListProductsResponse\x12g\n" +
	"\x12BulkImportProducts\x12'.tribecart.v1.BulkImportProductsRequest\x1a(.tribecart.v1.BulkImportProductsResponse\x12g\n" +
	"\x12BulkExportProducts\x12'.tribecart.v1.BulkExportProductsRequest\x1a(.tribecart.v1.BulkExportProductsResponseB,Z*github.com/tribecart/proto/tribecart/v1;v1b\x06proto3"

var (
	file_tribecart_v1_products_proto_rawDescOnce sync.Once
	file_tribecart_v1_products_proto_rawDescData []byte
)

func file_tribecart_v1_products_proto_rawDescGZIP() []byte {
	file_tribecart_v1_products_proto_rawDescOnce.Do(func() {
		file_tribecart_v1_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tribecart_v1_products_proto_rawDesc), len(file_tribecart_v1_products_proto_rawDesc)))
	})
	return file_tribecart_v1_products_proto_rawDescData
}

var file_tribecart_v1_products_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tribecart_v1_products_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_tribecart_v1_products_proto_goTypes = []any{
	(ProductStatus)(0),                   // 0: tribecart.v1.ProductStatus
	(ProductType)(0),                     // 1: tribecart.v1.ProductType
	(*Product)(nil),                      // 2: tribecart.v1.Product
	(*ProductVariant)(nil),               // 3: tribecart.v1.ProductVariant
	(*CreateProductRequest)(nil),         // 4: tribecart.v1.CreateProductRequest
	(*GetProductRequest)(nil),            // 5: tribecart.v1.GetProductRequest
	(*UpdateProductRequest)(nil),         // 6: tribecart.v1.UpdateProductRequest
	(*DeleteProductRequest)(nil),         // 7: tribecart.v1.DeleteProductRequest
	(*ListProductsRequest)(nil),          // 8: tribecart.v1.ListProductsRequest
	(*ListProductsResponse)(nil),         // 9: tribecart.v1.ListProductsResponse
	(*UpdateStockRequest)(nil),           // 10: tribecart.v1.UpdateStockRequest
	(*SearchProductsRequest)(nil),        // 11: tribecart.v1.SearchProductsRequest
	(*SearchProductsResponse)(nil),       // 12: tribecart.v1.SearchProductsResponse
	(*SearchAggregation)(nil),            // 13: tribecart.v1.SearchAggregation
	(*AggregationBucket)(nil),            // 14: tribecart.v1.AggregationBucket
	(*GetProductsByCategoryRequest)(nil), // 15: tribecart.v1.GetProductsByCategoryRequest
	(*BulkImportProductsRequest)(nil),    // 16: tribecart.v1.BulkImportProductsRequest
	(*ImportOptions)(nil),                // 17: tribecart.v1.ImportOptions
	(*BulkImportProductsResponse)(nil),   // 18: tribecart.v1.BulkImportProductsResponse
	(*ImportError)(nil),                  // 19: tribecart.v1.ImportError
	(*BulkExportProductsRequest)(nil),    // 20: tribecart.v1.BulkExportProductsRequest
	(*BulkExportProductsResponse)(nil),   // 21: tribecart.v1.BulkExportProductsResponse
	nil,                                  // 22: tribecart.v1.Product.SpecificationsEntry
	nil,                                  // 23: tribecart.v1.Product.MetadataEntry
	nil,                                  // 24: tribecart.v1.ProductVariant.AttributesEntry
	nil,                                  // 25: tribecart.v1.CreateProductRequest.SpecificationsEntry
	nil,                                  // 26: tribecart.v1.CreateProductRequest.MetadataEntry
	nil,                                  // 27: tribecart.v1.UpdateProductRequest.SpecificationsEntry
	nil,                                  // 28: tribecart.v1.UpdateProductRequest.MetadataEntry
	nil,                                  // 29: tribecart.v1.SearchProductsResponse.AggregationsEntry
	nil,                                  // 30: tribecart.v1.ImportOptions.FieldMappingsEntry
	nil,                                  // 31: tribecart.v1.ImportOptions.DefaultValuesEntry
	(*timestamppb.Timestamp)(nil),        // 32: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),        // 33: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                // 34: google.protobuf.Empty
}
var file_tribecart_v1_products_proto_depIdxs = []int32{
	1,  // 0: tribecart.v1.Product.type:type_name -> tribecart.v1.ProductType
	0,  // 1: tribecart.v1.Product.status:type_name -> tribecart.v1.ProductStatus
	22, // 2: tribecart.v1.Product.specifications:type_name -> tribecart.v1.Product.SpecificationsEntry
	32, // 3: tribecart.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	32, // 4: tribecart.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	32, // 5: tribecart.v1.Product.deleted_at:type_name -> google.protobuf.Timestamp
	23, // 6: tribecart.v1.Product.metadata:type_name -> tribecart.v1.Product.MetadataEntry
	3,  // 7: tribecart.v1.Product.variants:type_name -> tribecart.v1.ProductVariant
	24, // 8: tribecart.v1.ProductVariant.attributes:type_name -> tribecart.v1.ProductVariant.AttributesEntry
	32, // 9: tribecart.v1.ProductVariant.created_at:type_name -> google.protobuf.Timestamp
	32, // 10: tribecart.v1.ProductVariant.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 11: tribecart.v1.CreateProductRequest.type:type_name -> tribecart.v1.ProductType
	0,  // 12: tribecart.v1.CreateProductRequest.status:type_name -> tribecart.v1.ProductStatus
	25, // 13: tribecart.v1.CreateProductRequest.specifications:type_name -> tribecart.v1.CreateProductRequest.SpecificationsEntry
	3,  // 14: tribecart.v1.CreateProductRequest.variants:type_name -> tribecart.v1.ProductVariant
	26, // 15: tribecart.v1.CreateProductRequest.metadata:type_name -> tribecart.v1.CreateProductRequest.MetadataEntry
	33, // 16: tribecart.v1.UpdateProductRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 17: tribecart.v1.UpdateProductRequest.type:type_name -> tribecart.v1.ProductType
	0,  // 18: tribecart.v1.UpdateProductRequest.status:type_name -> tribecart.v1.ProductStatus
	27, // 19: tribecart.v1.UpdateProductRequest.specifications:type_name -> tribecart.v1.UpdateProductRequest.SpecificationsEntry
	3,  // 20: tribecart.v1.UpdateProductRequest.variants:type_name -> tribecart.v1.ProductVariant
	28, // 21: tribecart.v1.UpdateProductRequest.metadata:type_name -> tribecart.v1.UpdateProductRequest.MetadataEntry
	0,  // 22: tribecart.v1.ListProductsRequest.status:type_name -> tribecart.v1.ProductStatus
	2,  // 23: tribecart.v1.ListProductsResponse.products:type_name -> tribecart.v1.Product
	2,  // 24: tribecart.v1.SearchProductsResponse.products:type_name -> tribecart.v1.Product
	29, // 25: tribecart.v1.SearchProductsResponse.aggregations:type_name -> tribecart.v1.SearchProductsResponse.AggregationsEntry
	14, // 26: tribecart.v1.SearchAggregation.buckets:type_name -> tribecart.v1.AggregationBucket
	17, // 27: tribecart.v1.BulkImportProductsRequest.options:type_name -> tribecart.v1.ImportOptions
	30, // 28: tribecart.v1.ImportOptions.field_mappings:type_name -> tribecart.v1.ImportOptions.FieldMappingsEntry
	31, // 29: tribecart.v1.ImportOptions.default_values:type_name -> tribecart.v1.ImportOptions.DefaultValuesEntry
	19, // 30: tribecart.v1.BulkImportProductsResponse.errors:type_name -> tribecart.v1.ImportError
	32, // 31: tribecart.v1.BulkImportProductsResponse.started_at:type_name -> google.protobuf.Timestamp
	32, // 32: tribecart.v1.BulkImportProductsResponse.completed_at:type_name -> google.protobuf.Timestamp
	8,  // 33: tribecart.v1.BulkExportProductsRequest.filter:type_name -> tribecart.v1.ListProductsRequest
	32, // 34: tribecart.v1.BulkExportProductsResponse.started_at:type_name -> google.protobuf.Timestamp
	32, // 35: tribecart.v1.BulkExportProductsResponse.completed_at:type_name -> google.protobuf.Timestamp
	13, // 36: tribecart.v1.SearchProductsResponse.AggregationsEntry.value:type_name -> tribecart.v1.SearchAggregation
	4,  // 37: tribecart.v1.ProductService.CreateProduct:input_type -> tribecart.v1.CreateProductRequest
	5,  // 38: tribecart.v1.ProductService.GetProduct:input_type -> tribecart.v1.GetProductRequest
	6,  // 39: tribecart.v1.ProductService.UpdateProduct:input_type -> tribecart.v1.UpdateProductRequest
	7,  // 40: tribecart.v1.ProductService.DeleteProduct:input_type -> tribecart.v1.DeleteProductRequest
	8,  // 41: tribecart.v1.ProductService.ListProducts:input_type -> tribecart.v1.ListProductsRequest
	10, // 42: tribecart.v1.ProductService.UpdateStock:input_type -> tribecart.v1.UpdateStockRequest
	11, // 43: tribecart.v1.ProductService.SearchProducts:input_type -> tribecart.v1.SearchProductsRequest
	15, // 44: tribecart.v1.ProductService.GetProductsByCategory:input_type -> tribecart.v1.GetProductsByCategoryRequest
	16, // 45: tribecart.v1.ProductService.BulkImportProducts:input_type -> tribecart.v1.BulkImportProductsRequest
	20, // 46: tribecart.v1.ProductService.BulkExportProducts:input_type -> tribecart.v1.BulkExportProductsRequest
	2,  // 47: tribecart.v1.ProductService.CreateProduct:output_type -> tribecart.v1.Product
	2,  // 48: tribecart.v1.ProductService.GetProduct:output_type -> tribecart.v1.Product
	2,  // 49: tribecart.v1.ProductService.UpdateProduct:output_type -> tribecart.v1.Product
	34, // 50: tribecart.v1.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	9,  // 51: tribecart.v1.ProductService.ListProducts:output_type -> tribecart.v1.ListProductsResponse
	2,  // 52: tribecart.v1.ProductService.UpdateStock:output_type -> tribecart.v1.Product
	12, // 53: tribecart.v1.ProductService.SearchProducts:output_type -> tribecart.v1.SearchProductsResponse
	9,  // 54: tribecart.v1.ProductService.GetProductsByCategory:output_type -> tribecart.v1.ListProductsResponse
	18, // 55: tribecart.v1.ProductService.BulkImportProducts:output_type -> tribecart.v1.BulkImportProductsResponse
	21, // 56: tribecart.v1.ProductService.BulkExportProducts:output_type -> tribecart.v1.BulkExportProductsResponse
	47, // [47:57] is the sub-list for method output_type
	37, // [37:47] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_tribecart_v1_products_proto_init() }
func file_tribecart_v1_products_proto_init() {
	if File_tribecart_v1_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tribecart_v1_products_proto_rawDesc), len(file_tribecart_v1_products_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tribecart_v1_products_proto_goTypes,
		DependencyIndexes: file_tribecart_v1_products_proto_depIdxs,
		EnumInfos:         file_tribecart_v1_products_proto_enumTypes,
		MessageInfos:      file_tribecart_v1_products_proto_msgTypes,
	}.Build()
	File_tribecart_v1_products_proto = out.File
	file_tribecart_v1_products_proto_goTypes = nil
	file_tribecart_v1_products_proto_depIdxs = nil
}
